### PR TITLE
upgrade DET and django

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Review by proteusvacuum — APPROVED** [review]

**Comment by proteusvacuum** [comment]
Does a deploy need to happen on currently running instances? We did with the last DET upgrade because it was potentially causing data loss, although I guess this update isn't as critical.

**Comment by ctsims** [comment]
Does CCSync have the ability to do a regular check on the latest versions available and present a banner for sysadmins to update? If we occasionally have high priority updates to get processed it feels like that would give us a lot of peace of mind to reach downstream users.

**Comment by proteusvacuum** [comment]
@ctsims that functionality doesn't currently exist. Currently we are the sysadmins for all the known cc-sync instances.

**Comment by czue** [comment]
Yeah, though would be an interesting piece of functionality to build. :thinking: 

Agree at the moment it's probably fine to manage by hand and until we have more external sync users our efforts might be better served by making it easier for us to deploy to all known instances in a single command

**Comment by czue** [comment]
> Does a deploy need to happen on currently running instances?

I don't think it's urgent, but I may take care of it anyways to work towards this goal:

> making it easier for us to deploy to all known instances in a single command

**Comment by proteusvacuum** [comment]
> making it easier for us to deploy to all known instances in a single command

Good luck! Looking forward to seeing how you handle all the different jump servers and VPNs 😛

**Comment by czue** [comment]
> Good luck! Looking forward to seeing how you handle all the different jump servers and VPNs 

Easy: "we assume you have SSH access and DNS set up for all available machines".

**Pull request merged**
